import Link from "next/link";
import Navbar from "@/app/components/navbar";

export default function Home() {
  return (
    <div className="relative min-h-screen text-white overflow-hidden selection:bg-violet-500/30">
      {/* Background with Gradient Mesh */}
      <div className="fixed inset-0 bg-black z-[-1]" />
      <div className="fixed inset-0 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-violet-900/40 via-black to-black z-[-1]" />

      {/* Hero Section */}
      <section className="relative pt-32 pb-20 px-6">
        <div className="max-w-7xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-xs font-medium text-violet-300 mb-8 animate-fade-in-up">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-violet-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-violet-500"></span>
            </span>
            New: Text-to-Video Engine Live
          </div>

          <h1 className="text-5xl md:text-7xl font-bold tracking-tight mb-6 bg-clip-text text-transparent bg-gradient-to-b from-white to-white/60 animate-fade-in-up stagger-1">
            Create Viral Videos <br />
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-violet-400 to-pink-400">
              with AI Intelligence
            </span>
          </h1>

          <p className="text-lg md:text-xl text-slate-400 max-w-2xl mx-auto mb-10 leading-relaxed animate-fade-in-up stagger-2">
            Transform text into high-definition videos, AI avatars, and social content in seconds.
            The creative studio for the next generation of brands.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 animate-fade-in-up stagger-3">
            <Link
              href="/studio"
              className="px-8 py-4 rounded-full bg-white text-black font-bold text-lg hover:scale-105 transition-transform duration-300 shadow-[0_0_40px_rgba(255,255,255,0.3)] flex items-center gap-2"
            >
              <span>✨</span> Open Studio
            </Link>
            <Link
              href="/pricing"
              className="px-8 py-4 rounded-full bg-white/5 border border-white/10 text-white font-medium hover:bg-white/10 transition-colors backdrop-blur-sm"
            >
              View Pricing
            </Link>
          </div>

          {/* Video / Visual Demo */}
          <div className="mt-20 relative max-w-5xl mx-auto rounded-xl overflow-hidden shadow-2xl border border-white/10 bg-black/50 backdrop-blur-xl aspect-video animate-fade-in-up stagger-4 group">
            <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent z-10" />

            {/* Placeholder for Demo Video - You can replace src with a real demo video */}
            <video
              autoPlay
              loop
              muted
              playsInline
              className="w-full h-full object-cover opacity-80 group-hover:opacity-100 transition-opacity duration-700"
              poster="https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=2564&auto=format&fit=crop"
            >
              {/* Fallback pattern if video not available, or use a sample from public URL */}
              <source src="https://cdn.coverr.co/videos/coverr-futuristic-city-4k-5264/1080p.mp4" type="video/mp4" />
            </video>

            <div className="absolute bottom-8 left-8 z-20 text-left">
              <div className="flex items-center gap-2 mb-2">
                <div className="w-8 h-8 rounded-full bg-violet-500/20 flex items-center justify-center border border-violet-500/50">
                  🤖
                </div>
                <span className="text-sm font-medium text-violet-300">Generated by Nexora AI</span>
              </div>
              <p className="text-2xl font-bold">"Futuristic City at Sunset"</p>
            </div>
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="py-32 px-6 relative z-10">
        <div className="max-w-7xl mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              { title: "Text-to-Video", desc: "Turn simple prompts into cinematic 4K videos.", icon: "🎥" },
              { title: "AI Avatars", desc: "Create realistic talking heads for your brand.", icon: "👤" },
              { title: "Smart Scheduling", desc: "Auto-post your creations to Instagram.", icon: "📅" }
            ].map((feature, i) => (
              <div key={i} className="p-8 rounded-2xl bg-white/5 border border-white/10 hover:bg-white/10 transition-colors group">
                <div className="text-4xl mb-4 group-hover:scale-110 transition-transform duration-300">{feature.icon}</div>
                <h3 className="text-xl font-bold mb-2">{feature.title}</h3>
                <p className="text-slate-400">{feature.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

    </div>
  );
}
